site_name: "Tree Coin Whitepaper"
site_url: https://whitepaper.treecoin.online
site_description: "An alternative economic system for financing Tree protection, Eco-villages and Sustainability"
site_author: "The Tree Coin Roots collective"
docs_dir: "docs/en"
site_dir: 'generated/en'
site_author: "The Tree Coin Roots collective"
copyright: "2022 Tree Coin"
repo_name: "GitHub"
repo_url: https://github.com/Tree-Coin/Whitepaper/
# edit_uri: edit/mkdocs/docs/
edit_uri: ""
# docs_dir: "../../docs/en"
# site_dir: '../../generated/en'
use_directory_urls: true
dev_addr: "127.0.0.1:4000"
copyright: "Copyright &copy; 2022 Tree Coin"
extra:
  # homepage: https://treecoin.online/
  version:
    provider: mike
    default: latest
  generator: false
  # social:
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/squidfunk
    #   name: squidfunk on Twitter
  alternate:
    - name: English
      link: ./
      lang: en
    - name: Italiano
      link: ../it/
      lang: it
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  #   cookies:
  #     analytics:
  #       name: Google Analytics
  #       checked: false
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/jquery/jquery.min.js
  - assets/javascripts/main.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: "index.md"
  - Our philosophy:
    - The debt problem: "our-philosophy/the-debt-problem.md"
    - The solution: "our-philosophy/the-solution.md"
    - Trees benefit: "our-philosophy/trees-benefit.md"
    - Requirements: "our-philosophy/requirements.md"
  - Technical features:
    - The Tree Coin logo: "technical-features/the-tree-coin-logo.md"
    - Technical plotting details: "technical-features/technical-plotting-details.md"
    - The Tree Coin credit-representation: "technical-features/the-tree-credit-representation.md"
    - Table of barter ratio: "technical-features/table-of-proposed-barter-ratio-per-tree-coin.md"
  - About the project:
    # - How to get Tree Coins: "about/how-to-get.md"
    - Governance: "about/governance.md"
    - Licenses: "about/licenses.md"
  - UN Sustainable Development:
    - Trees and sustainable development: "un-sustainable-development/trees-and-sustainable-development.md"
    - Participation to UN Global Goals: "un-sustainable-development/participation-to-un-global-goals.md"
markdown_extensions:
  - attr_list: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # options:
      #   custom_icons:
      #     - overrides/.icons
theme:
  name: material
  custom_dir: 'overrides/'
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  features:
    - content.code.annotate
    - header.autohide
    - instant
    - navigation.expand
    # - navigation.indexes
    - navigation.instant
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.suggest
    - tabs
    - toc.follow
    - toc.integrate
  logo: assets/images/spring_500.png
  favicon: assets/images/favicon.ico
  # icon:
  #   repo: fontawesome/brands/github
  language: en
  highlightjs: true
  palette:
    - scheme: default
      primary: light green
      accent: lime
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"
plugins:
  # - mike:
  #     version_selector: false
  #     css_dir: _css
  #     javascript_dir: _js
  #     canonical_version: null
  - search:
      lang:
        - en
        - it
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        it:
          name: Italiano
      nav_translations:
        it:
          Our philosophy: "La nostra filosofia"
          Technical features: "Caratteristiche tecniche"
          About the project: "Riguardo al progetto"
          UN Sustainable Development: "Sviluppo sostenibile dell'ONU"
  - awesome-pages:
      collapse_single_pages: false
  - mkdocs-nav-enhancements
  - exclude:
      glob:
        # - exclude/this/path/*
        # - "*.tmp"
        # - "*.pdf"
        # - "*.gz"
      regex:
        # - ".*\.(tmp|bin|tar)$"
markdown_extensions:
  - abbr
  - attr_list
  - codehilite
  - def_list
  # - fontawesome_markdown
  - footnotes
  - meta
  - md_in_html
  # - search
  - smarty
  # - toc:
  #     permalink: true
  #     separator: "_"
  - sane_lists
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tilde
  - tables
